# -*- coding: utf-8 -*-
"""ine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANQIwdbvx44sSyV7fz0YhbtqAmOQfMYC
"""

def Add(x,y):
  return x+y

def Subtract(x,y):
  return x-y

def Multiply(x,y):
  return x*y

def Divide(x,y):
  if x or y == 0:
    print("Invalid value for denominator, cant't divide by 0!")
  else:
    return x/y

def square(x):
    return x*x


def power(x, y):
    pass


def sqrt(x):
    pass

print(Divide(2,0))